More wording improvements.

diff --git a/contrib/pg_upgrade/pg_upgrade b/contrib/pg_upgrade/pg_upgrade
--- a/contrib/pg_upgrade/pg_upgrade
+++ b/contrib/pg_upgrade/pg_upgrade
@@ -31,7 +31,7 @@ CUR_VERSION="7.2"
 
 trap "rm -f /tmp/$$.*" 0 1 2 3 15
 
-BASENAME=`basename "$0`
+BASENAME=`basename "$0"`
 PHASE=""
 
 if [ "$#" -eq 1 ]
@@ -294,7 +294,7 @@ then
 	fi
 	echo
 	echo
-	echo "Plase 1 completed."
+	echo "$BASENAME phase 1 completed."
 	echo "Continue with the steps outlined in the $BASENAME manual page."
 	exit 0
 fi
@@ -545,12 +545,13 @@ if [ "$SRC_VERSION" = "7.1" -o \
 then	echo "Set sequence values..."
 	psql -d template1 -At < "$INFODIR"/setval
 	if [ $? -ne 0 ]
-	then	echo "There were errors during int4 sequence restore.  Exiting." 1>&2
+	then	echo "There were errors during int4 sequence restoration.  Exiting." 1>&2
 		exit 1
 	fi
 fi
 
 echo
 echo
+echo "$BASENAME phase 2 completed."
 echo "You may remove the old database files with 'rm -r $INFODIR'."
 exit 0
