Update startup scripts for Linux and FreeBSD.
Kevin Grittner

diff --git a/contrib/start-scripts/freebsd b/contrib/start-scripts/freebsd
--- a/contrib/start-scripts/freebsd
+++ b/contrib/start-scripts/freebsd
@@ -36,7 +36,14 @@ DAEMON="$prefix/bin/postmaster"
 PGCTL="$prefix/bin/pg_ctl"
 
 # Only start if we can find the postmaster.
-test -x "$DAEMON" || exit 0
+test -x $DAEMON ||
+{
+	echo "$DAEMON not found"
+	if [ "$1" = "stop" ]
+	then exit 0
+	else exit 5
+	fi
+}
 
 case $1 in
     start)
diff --git a/contrib/start-scripts/linux b/contrib/start-scripts/linux
--- a/contrib/start-scripts/linux
+++ b/contrib/start-scripts/linux
@@ -64,7 +64,15 @@ PGCTL="$prefix/bin/pg_ctl"
 set -e
 
 # Only start if we can find the postmaster.
-test -x $DAEMON || exit 0
+test -x $DAEMON ||
+{
+	echo "$DAEMON not found"
+	if [ "$1" = "stop" ]
+	then exit 0
+	else exit 5
+	fi
+}
+
 
 # Parse command line parameters.
 case $1 in
