Add checking for valid database encoding.

diff --git a/src/bin/scripts/createdb b/src/bin/scripts/createdb
--- a/src/bin/scripts/createdb
+++ b/src/bin/scripts/createdb
@@ -145,6 +145,10 @@ then
 	then
 		echo "$CMDNAME: \"$MB\" is not a valid encoding name" 1>&2
 		exit 1
+	elif [ $mbcode -gt 31 ]
+	then
+		echo "$CMDNAME: $MB cannot be used as a database encoding" 1>&2
+		exit 1
 	fi
 fi
 
