Fix param handling of create* admin scripts as described months ago. Properly handles default values.

diff --git a/src/bin/scripts/createuser b/src/bin/scripts/createuser
--- a/src/bin/scripts/createuser
+++ b/src/bin/scripts/createuser
@@ -123,6 +123,11 @@ do
 		;;
          *)
 		NewUser="$1"
+		if [ "$#" -ne 1 ]; then
+			echo "$CMDNAME: invalid option: $2" 1>&2
+	                echo "Try '$CMDNAME --help' for more information." 1>&2
+			exit 1
+		fi
 		;;
     esac
     shift;
diff --git a/src/bin/scripts/dropdb b/src/bin/scripts/dropdb
--- a/src/bin/scripts/dropdb
+++ b/src/bin/scripts/dropdb
@@ -89,6 +89,11 @@ do
 		;;
 	 *)
 		dbname="$1"
+		if [ "$#" -ne 1 ]; then
+			echo "$CMDNAME: invalid option: $2" 1>&2
+	                echo "Try '$CMDNAME --help' for more information." 1>&2
+			exit 1
+		fi
 		;;
     esac
     shift
